AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: ytmp3 cloud

Resources:
  Ytmp3Downloader:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      Handler: mp3-downloader/main.handler
      Runtime: python3.9
      Timeout: 300

  Ytmp3Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: Ytmp3Downloader
      Description: REST API for ytmp3-cloud
      ProtocolType: HTTP
      Version: v1.0.0

  Ytmp3ApiDownloaderIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref Ytmp3Api
      Description: Lambda Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Join
        - ""
        - - "arn:"
          - !Ref "AWS::Partition"
          - ":apigateway:"
          - !Ref "AWS::Region"
          - ":lambda:path/2015-03-31/functions/"
          - !GetAtt Ytmp3Downloader.Arn
          - "/invocations"
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"

  Ytmp3ApiDownloaderRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Ytmp3Api
      RouteKey: "GET /mp3/{videoId}"
      Target: !Join
        - ""
        - - "integrations/"
          - !Ref Ytmp3ApiDownloaderIntegration

  Ytmp3ApiDefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: $default
      ApiId: !Ref Ytmp3Api

  Deployment:
    Type: "AWS::ApiGatewayV2::Deployment"
    DependsOn:
      - Ytmp3ApiDownloaderRoute
    Properties:
      ApiId: !Ref Ytmp3Api
      StageName: $default

  Ytmp3ApiDownloaderPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Ytmp3Downloader.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ""
        - - "arn:aws:execute-api:"
          - !Ref "AWS::Region"
          - ":"
          - !Ref "AWS::AccountId"
          - ":"
          - !Ref Ytmp3Api
          - "/*/GET/mp3/*"
