AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: ytmp3 cloud

Parameters:
  Ytmp3DownloaderDockerImageUri:
    Type: String
    Description: Docker Image URI for ytmp3-downloader lambda function

  Ytmp3StoreBucketName:
    Type: String
    Description: Name of ytmp3-store bucket (must be unique)

Resources:
  Ytmp3DownloaderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "ytmp3-downloader-queue"
      VisibilityTimeout: 300

  Ytmp3DownloaderQueuePolicy: 
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Ref Ytmp3DownloaderQueue
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - "SQS:*" 
            Effect: "Allow"
            Resource: !GetAtt Ytmp3Downloader.Arn     

  Ytmp3Store:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref Ytmp3StoreBucketName

  Ytmp3DownloaderRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ytmp3-downloader-role-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: !GetAtt Ytmp3Store.Arn
              - Effect: Allow
                Action: 
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                Resource: !GetAtt Ytmp3DownloaderQueue.Arn
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  Ytmp3Downloader:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref Ytmp3DownloaderDockerImageUri
      Timeout: 300
      Role: !GetAtt Ytmp3DownloaderRole.Arn
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt Ytmp3DownloaderQueue.Arn
      Environment:
        Variables:
          YTMP3_STORE_BUCKET_NAME: !Ref Ytmp3StoreBucketName

  Ytmp3DispatcherRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ytmp3-downloader-role-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "sqs:*"
                Resource: !GetAtt Ytmp3DownloaderQueue.Arn
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  Ytmp3Dispatcher:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: ytmp3-dispatcher/
      Handler: main.handler
      Runtime: python3.9
      Timeout: 300
      Role: !GetAtt Ytmp3DispatcherRole.Arn
      Environment:
        Variables:
          YTMP3_DOWNLOADER_QUEUE: !GetAtt Ytmp3DownloaderQueue.Arn

  Ytmp3Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: Ytmp3CloudApi
      Description: REST API for ytmp3-cloud
      ProtocolType: HTTP
      Version: v1.0.0

  Ytmp3ApiDispatcherIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref Ytmp3Api
      Description: Lambda Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Join
        - ""
        - - "arn:"
          - !Ref "AWS::Partition"
          - ":apigateway:"
          - !Ref "AWS::Region"
          - ":lambda:path/2015-03-31/functions/"
          - !GetAtt Ytmp3Dispatcher.Arn
          - "/invocations"
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"

  Ytmp3ApiDispatcherRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Ytmp3Api
      RouteKey: "GET /mp3/{videoId}"
      Target: !Join
        - ""
        - - "integrations/"
          - !Ref Ytmp3ApiDispatcherIntegration

  Ytmp3ApiDefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: $default
      ApiId: !Ref Ytmp3Api

  Deployment:
    Type: "AWS::ApiGatewayV2::Deployment"
    DependsOn:
      - Ytmp3ApiDispatcherRoute
    Properties:
      ApiId: !Ref Ytmp3Api
      StageName: $default

  Ytmp3ApiDispatcherPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Ytmp3Dispatcher.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ""
        - - "arn:aws:execute-api:"
          - !Ref "AWS::Region"
          - ":"
          - !Ref "AWS::AccountId"
          - ":"
          - !Ref Ytmp3Api
          - "/*/GET/mp3/*"
